version: '3.4'

services:
  listadecomprasinteligente.api:
    image: ${DOCKER_REGISTRY-}listadecomprasinteligenteapi
    build:
      context: .
      dockerfile: ListaDeComprasInteligente.API/Dockerfile
    networks:
      - browser
  chrome:
    image: browserless/chrome:latest
    networks:
      - browser

networks:
  browser:
    name: browser